const response = {
    header: { resultCode: '00', resultMsg: 'NORMAL_SERVICE' },
    body: {
        dataType: 'JSON',
        items: {
            item: [
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'LGT',
                    fcstDate: '20230606',
                    fcstTime: '1800',
                    fcstValue: '0',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'LGT',
                    fcstDate: '20230606',
                    fcstTime: '1900',
                    fcstValue: '0',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'LGT',
                    fcstDate: '20230606',
                    fcstTime: '2000',
                    fcstValue: '0',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'LGT',
                    fcstDate: '20230606',
                    fcstTime: '2100',
                    fcstValue: '0',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'LGT',
                    fcstDate: '20230606',
                    fcstTime: '2200',
                    fcstValue: '0',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'LGT',
                    fcstDate: '20230606',
                    fcstTime: '2300',
                    fcstValue: '0',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'PTY',
                    fcstDate: '20230606',
                    fcstTime: '1800',
                    fcstValue: '0',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'PTY',
                    fcstDate: '20230606',
                    fcstTime: '1900',
                    fcstValue: '0',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'PTY',
                    fcstDate: '20230606',
                    fcstTime: '2000',
                    fcstValue: '0',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'PTY',
                    fcstDate: '20230606',
                    fcstTime: '2100',
                    fcstValue: '0',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'PTY',
                    fcstDate: '20230606',
                    fcstTime: '2200',
                    fcstValue: '0',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'PTY',
                    fcstDate: '20230606',
                    fcstTime: '2300',
                    fcstValue: '0',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'RN1',
                    fcstDate: '20230606',
                    fcstTime: '1800',
                    fcstValue: '강수없음',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'RN1',
                    fcstDate: '20230606',
                    fcstTime: '1900',
                    fcstValue: '강수없음',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'RN1',
                    fcstDate: '20230606',
                    fcstTime: '2000',
                    fcstValue: '강수없음',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'RN1',
                    fcstDate: '20230606',
                    fcstTime: '2100',
                    fcstValue: '강수없음',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'RN1',
                    fcstDate: '20230606',
                    fcstTime: '2200',
                    fcstValue: '강수없음',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'RN1',
                    fcstDate: '20230606',
                    fcstTime: '2300',
                    fcstValue: '강수없음',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'SKY',
                    fcstDate: '20230606',
                    fcstTime: '1800',
                    fcstValue: '4',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'SKY',
                    fcstDate: '20230606',
                    fcstTime: '1900',
                    fcstValue: '4',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'SKY',
                    fcstDate: '20230606',
                    fcstTime: '2000',
                    fcstValue: '4',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'SKY',
                    fcstDate: '20230606',
                    fcstTime: '2100',
                    fcstValue: '4',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'SKY',
                    fcstDate: '20230606',
                    fcstTime: '2200',
                    fcstValue: '4',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'SKY',
                    fcstDate: '20230606',
                    fcstTime: '2300',
                    fcstValue: '4',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'T1H',
                    fcstDate: '20230606',
                    fcstTime: '1800',
                    fcstValue: '18',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'T1H',
                    fcstDate: '20230606',
                    fcstTime: '1900',
                    fcstValue: '18',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'T1H',
                    fcstDate: '20230606',
                    fcstTime: '2000',
                    fcstValue: '17',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'T1H',
                    fcstDate: '20230606',
                    fcstTime: '2100',
                    fcstValue: '17',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'T1H',
                    fcstDate: '20230606',
                    fcstTime: '2200',
                    fcstValue: '17',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'T1H',
                    fcstDate: '20230606',
                    fcstTime: '2300',
                    fcstValue: '17',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'REH',
                    fcstDate: '20230606',
                    fcstTime: '1800',
                    fcstValue: '90',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'REH',
                    fcstDate: '20230606',
                    fcstTime: '1900',
                    fcstValue: '90',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'REH',
                    fcstDate: '20230606',
                    fcstTime: '2000',
                    fcstValue: '90',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'REH',
                    fcstDate: '20230606',
                    fcstTime: '2100',
                    fcstValue: '90',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'REH',
                    fcstDate: '20230606',
                    fcstTime: '2200',
                    fcstValue: '90',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'REH',
                    fcstDate: '20230606',
                    fcstTime: '2300',
                    fcstValue: '90',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'UUU',
                    fcstDate: '20230606',
                    fcstTime: '1800',
                    fcstValue: '3.1',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'UUU',
                    fcstDate: '20230606',
                    fcstTime: '1900',
                    fcstValue: '3.3',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'UUU',
                    fcstDate: '20230606',
                    fcstTime: '2000',
                    fcstValue: '2.4',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'UUU',
                    fcstDate: '20230606',
                    fcstTime: '2100',
                    fcstValue: '2',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'UUU',
                    fcstDate: '20230606',
                    fcstTime: '2200',
                    fcstValue: '2.2',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'UUU',
                    fcstDate: '20230606',
                    fcstTime: '2300',
                    fcstValue: '2.6',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'VVV',
                    fcstDate: '20230606',
                    fcstTime: '1800',
                    fcstValue: '2.9',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'VVV',
                    fcstDate: '20230606',
                    fcstTime: '1900',
                    fcstValue: '3',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'VVV',
                    fcstDate: '20230606',
                    fcstTime: '2000',
                    fcstValue: '3.8',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'VVV',
                    fcstDate: '20230606',
                    fcstTime: '2100',
                    fcstValue: '4.1',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'VVV',
                    fcstDate: '20230606',
                    fcstTime: '2200',
                    fcstValue: '3.9',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'VVV',
                    fcstDate: '20230606',
                    fcstTime: '2300',
                    fcstValue: '4.5',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'VEC',
                    fcstDate: '20230606',
                    fcstTime: '1800',
                    fcstValue: '227',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'VEC',
                    fcstDate: '20230606',
                    fcstTime: '1900',
                    fcstValue: '228',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'VEC',
                    fcstDate: '20230606',
                    fcstTime: '2000',
                    fcstValue: '212',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'VEC',
                    fcstDate: '20230606',
                    fcstTime: '2100',
                    fcstValue: '206',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'VEC',
                    fcstDate: '20230606',
                    fcstTime: '2200',
                    fcstValue: '209',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'VEC',
                    fcstDate: '20230606',
                    fcstTime: '2300',
                    fcstValue: '210',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'WSD',
                    fcstDate: '20230606',
                    fcstTime: '1800',
                    fcstValue: '4',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'WSD',
                    fcstDate: '20230606',
                    fcstTime: '1900',
                    fcstValue: '4',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'WSD',
                    fcstDate: '20230606',
                    fcstTime: '2000',
                    fcstValue: '4',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'WSD',
                    fcstDate: '20230606',
                    fcstTime: '2100',
                    fcstValue: '5',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'WSD',
                    fcstDate: '20230606',
                    fcstTime: '2200',
                    fcstValue: '4',
                    nx: 37,
                    ny: 123,
                },
                {
                    baseDate: '20230606',
                    baseTime: '1730',
                    category: 'WSD',
                    fcstDate: '20230606',
                    fcstTime: '2300',
                    fcstValue: '5',
                    nx: 37,
                    ny: 123,
                },
            ],
        },
        pageNo: 1,
        numOfRows: 1000,
        totalCount: 60,
    },
}
